### ISSUE TITLE
MAX Cube Radiator Thermostat

### ISSUE THREAD

**Issue by Speedymax02** [nymea/nymea-plugins#210]
I connected nymea to my MaxCube. Unfortunately, only the wall thermostats were taken over. My radiator thermostats are not shown.

**Comment by mzanetti** [comment]
The fix will be included in the next release. Thanks for the report.

**Comment by mzanetti** [comment]
Ok, during QA of the release we've found some more issues in the Max! Cube plugin. I have done my best to fix them now and that should have improved the overall experience for this device a lot. Please report back how it goes once 0.18 is released (or - if you want to test right away, enable the testing repository in the system settings and update from there)
