### ISSUE TITLE
OneWire: Passing custom arguments is too complicated

### ISSUE THREAD

**Issue by mzanetti** [nymea/nymea-plugins#298]
Having the user deal with "--w1" and stuff is too complicated, or let's say, does not qualify for nymeas "easy to the user" standards.

There should be a set of ComboBoxes, Checkboxes and whatnot with a nice description what they do and they should compose the actual command line args themselves.

https://forum.nymea.io/t/ic2-ds18b20-temperature-sensors/280/9

**Comment by Boernsman** [comment]
https://github.com/nymea/nymea-plugins/pull/307
