### ISSUE TITLE
Lidl powersockets stopped working after rel 0.26 

### ISSUE THREAD

**Issue by Ollipake** [nymea/nymea-plugins#404]
Lidl/Silvercrest power sockets stopped working. Right after update it said in red:"Plugin for this thing is not installed!". 
When trying to pair the device to zigbee network, it doed not show up as a power socket thing. 

ps. One Xiaomi motion sensor is working OK, so the problem is related to power sockets.

Joining process from debug interface:

 I | ZigbeeNetwork: Received unhandled broadcast ZDO indication APSDE-DATA.indication(Group address:"0xfffc", Destination EP:"0x01", Source EP:"0x00", Source NWK address:"0x0000", Zigbee::ZigbeeProfileDevice, ZigbeeDeviceProfile::MgmtPermitJoinRequest, ASDU: "0x05 0x00 0x01", LQI: 17, RSSI: 21dBm)
 I | ZigbeeNetwork: Finish network reply ZigbeeNetworkReply(0x166dcc0) ZigbeeNetworkReply::ErrorNoError
 I | ZigbeeNetwork: Network request sent successfully to device Request(ID:5, Zigbee::ZigbeeProfileDevice, ZigbeeDeviceProfile::MgmtPermitJoinRequest, Group address:"0xfffc", Destination EP:"0x00", Source EP:"0x00", Radius:10, QFlags<Zigbee::ZigbeeTxOption>(), "0x05 0x00 0x01")
 I | ZigbeeNetwork: Permit join request finished successfully
 I | ZigbeeNetwork: Set permit join configuration request finished Deconz::StatusCodeSuccess
 I | Zigbee: Set permit joining in network ZigbeeNetwork(00:21:2E:FF:FF:06:AA:5E, {d99f642d-1bc4-4d0f-8a20-53210f4773df}, Zigbee::ZigbeeBackendTypeDeconz, Channel: 15, ZigbeeNetwork::StateRunning) to 120 seconds "0xfffc"
 I | ZigbeeNetwork: Set permit join for 120 s on "0xfffc"
 I | Zigbee: Network permit joining changed "{d99f642d-1bc4-4d0f-8a20-53210f4773df}" true
 I | ZigbeeNetwork: Send permit join request "0xfffc" 120 s
 I | ZigbeeNetwork: Received unhandled broadcast ZDO indication APSDE-DATA.indication(Group address:"0xfffc", Destination EP:"0x01", Source EP:"0x00", Source NWK address:"0x0000", Zigbee::ZigbeeProfileDevice, ZigbeeDeviceProfile::MgmtPermitJoinRequest, ASDU: "0x06 0x78 0x01", LQI: 17, RSSI: 21dBm)
 I | ZigbeeNetwork: Finish network reply ZigbeeNetworkReply(0xad20c8f0) ZigbeeNetworkReply::ErrorNoError
 I | ZigbeeNetwork: Network request sent successfully to device Request(ID:6, Zigbee::ZigbeeProfileDevice, ZigbeeDeviceProfile::MgmtPermitJoinRequest, Group address:"0xfffc", Destination EP:"0x00", Source EP:"0x00", Radius:10, QFlags<Zigbee::ZigbeeTxOption>(), "0x06 0x78 0x01")
 I | ZigbeeNetwork: Permit join request finished successfully
 I | ZigbeeNetwork: Set permit join configuration request finished Deconz::StatusCodeSuccess
 I | ZigbeeNetwork: Device announced "0xe31f" "84:2E:14:FF:FE:5B:F2:4E" "0x8e"
 I | ZigbeeNetwork: Finish network reply ZigbeeNetworkReply(0xad2397d8) ZigbeeNetworkReply::ErrorNoError
 I | ZigbeeNetwork: Network request sent successfully to device Request(ID:7, Zigbee::ZigbeeProfileDevice, ZigbeeDeviceProfile::NodeDescriptorRequest, NWK address:"0xe31f", Destination EP:"0x00", Source EP:"0x00", Radius:0, QFlags<Zigbee::ZigbeeTxOption>(ZigbeeTxOptionAckTransmission), "0x00 0x1f 0xe3")
 I | ZigbeeNetwork: Finish network reply ZigbeeNetworkReply(0xad2397d8) ZigbeeNetworkReply::ErrorNoError
 I | ZigbeeNetwork: Network request sent successfully to device Request(ID:8, Zigbee::ZigbeeProfileDevice, ZigbeeDeviceProfile::PowerDescriptorRequest, NWK address:"0xe31f", Destination EP:"0x00", Source EP:"0x00", Radius:0, QFlags<Zigbee::ZigbeeTxOption>(ZigbeeTxOptionAckTransmission), "0x01 0x1f 0xe3")
 I | ZigbeeNetwork: Finish network reply ZigbeeNetworkReply(0xad2397d8) ZigbeeNetworkReply::ErrorNoError
 I | ZigbeeNetwork: Network request sent successfully to device Request(ID:9, Zigbee::ZigbeeProfileDevice, ZigbeeDeviceProfile::ActiveEndpointsRequest, NWK address:"0xe31f", Destination EP:"0x00", Source EP:"0x00", Radius:0, QFlags<Zigbee::ZigbeeTxOption>(ZigbeeTxOptionAckTransmission), "0x02 0x1f 0xe3")
 I | ZigbeeNetwork: Finish network reply ZigbeeNetworkReply(0xad2397d8) ZigbeeNetworkReply::ErrorNoError
 I | ZigbeeNetwork: Network request sent successfully to device Request(ID:10, Zigbee::ZigbeeProfileDevice, ZigbeeDeviceProfile::SimpleDescriptorRequest, NWK address:"0xe31f", Destination EP:"0x00", Source EP:"0x00", Radius:0, QFlags<Zigbee::ZigbeeTxOption>(ZigbeeTxOptionAckTransmission), "0x03 0x1f 0xe3 0x0b")
 I | ZigbeeNetwork: Finish network reply ZigbeeNetworkReply(0xad2397d8) ZigbeeNetworkReply::ErrorNoError
 I | ZigbeeNetwork: Network request sent successfully to device Request(ID:11, Zigbee::ZigbeeProfileDevice, ZigbeeDeviceProfile::SimpleDescriptorRequest, NWK address:"0xe31f", Destination EP:"0x00", Source EP:"0x00", Radius:0, QFlags<Zigbee::ZigbeeTxOption>(ZigbeeTxOptionAckTransmission), "0x04 0x1f 0xe3 0xf2")
 I | ZigbeeNetwork: Finish network reply ZigbeeNetworkReply(0xad2397d8) ZigbeeNetworkReply::ErrorNoError
 I | ZigbeeNetwork: Network request sent successfully to device Request(ID:12, Zigbee::ZigbeeProfileHomeAutomation, ZigbeeClusterLibrary::ClusterIdBasic, NWK address:"0xe31f", Destination EP:"0x0b", Source EP:"0x01", Radius:0, QFlags<Zigbee::ZigbeeTxOption>(ZigbeeTxOptionAckTransmission), "0x10 0x00 0x00 0x04 0x00")
 I | ZigbeeNetwork: Finish network reply ZigbeeNetworkReply(0xad223430) ZigbeeNetworkReply::ErrorNoError
 I | ZigbeeNetwork: Network request sent successfully to device Request(ID:13, Zigbee::ZigbeeProfileHomeAutomation, ZigbeeClusterLibrary::ClusterIdBasic, NWK address:"0xe31f", Destination EP:"0x0b", Source EP:"0x01", Radius:0, QFlags<Zigbee::ZigbeeTxOption>(ZigbeeTxOptionAckTransmission), "0x10 0x00 0x00 0x05 0x00")
 W | ZigbeeCluster: Attribute status record "0x4000" finished with error ZigbeeClusterLibrary::StatusUnsupportedAttribute
 I | ZigbeeNetwork: Finish network reply ZigbeeNetworkReply(0xad21cb50) ZigbeeNetworkReply::ErrorNoError
 I | ZigbeeNetwork: Network request sent successfully to device Request(ID:14, Zigbee::ZigbeeProfileHomeAutomation, ZigbeeClusterLibrary::ClusterIdBasic, NWK address:"0xe31f", Destination EP:"0x0b", Source EP:"0x01", Radius:0, QFlags<Zigbee::ZigbeeTxOption>(ZigbeeTxOptionAckTransmission), "0x10 0x00 0x00 0x00 0x40")
 W | ZigbeeCluster: Attribute status record "0x4000" finished with error ZigbeeClusterLibrary::StatusUnsupportedAttribute
 I | ZigbeeNetwork: Add node ZigbeeNode(0xe31f, 84:2E:14:FF:FE:5B:F2:4E, _TZ3000_kdi2o9m6, TS011F, End device, RxOn:true)
 I | Zigbee: Node added to ZigbeeNetwork(00:21:2E:FF:FF:06:AA:5E, {d99f642d-1bc4-4d0f-8a20-53210f4773df}, Zigbee::ZigbeeBackendTypeDeconz, Channel: 15, ZigbeeNetwork::StateRunning) ZigbeeNode(0xe31f, 84:2E:14:FF:FE:5B:F2:4E, _TZ3000_kdi2o9m6, TS011F, End device, RxOn:true)
 I | Zigbee: --> ZigbeeNode(0xe31f, 84:2E:14:FF:FE:5B:F2:4E, _TZ3000_kdi2o9m6, TS011F, End device, RxOn:true)
 I | Zigbee:   ZigbeeNodeEndpoint(0x0b, Zigbee::ZigbeeProfileHomeAutomation, Zigbee::HomeAutomationDeviceOnOffPlugin)
 I | Zigbee:   Manufacturer: "_TZ3000_kdi2o9m6"
 I | Zigbee:   Model "TS011F"
 I | Zigbee:     Input clusters ( 5 )
 I | Zigbee:      - ZigbeeCluster(0x0003, Identify, Servers)
 I | Zigbee:      - ZigbeeCluster(0x0004, Groups, Servers)
 I | Zigbee:      - ZigbeeCluster(0x0005, Scenes, Servers)
 I | Zigbee:      - ZigbeeCluster(0x0006, OnOff, Servers)
 I | Zigbee:      - ZigbeeCluster(0x0000, Basic, Servers)
 I | Zigbee:        -  ZigbeeClusterAttribute(0x0004, ZigbeeDataType(Character string, _TZ3000_kdi2o9m6) ) 
 I | Zigbee:        -  ZigbeeClusterAttribute(0x0005, ZigbeeDataType(Character string, TS011F) ) 
 I | Zigbee:     Output clusters ( 2 )
 I | Zigbee:      - ZigbeeCluster(0x0019, OtaUpgrade, Client)
 I | Zigbee:      - ZigbeeCluster(0x000a, Time, Client)
 I | Zigbee:   ZigbeeNodeEndpoint(0xf2, Zigbee::ZigbeeProfileGreenPower, Zigbee::GreenPowerDeviceProxyMinimum)
 I | Zigbee:     Input clusters ( 0 )
 I | Zigbee:     Output clusters ( 1 )
 I | Zigbee:      - ZigbeeCluster(0x0021, GreenPower, Client)
 I | ZigbeeResource: ZigbeeNode(0xe31f, 84:2E:14:FF:FE:5B:F2:4E, _TZ3000_kdi2o9m6, TS011F, End device, RxOn:true) joined the network ZigbeeNetwork(00:21:2E:FF:FF:06:AA:5E, {d99f642d-1bc4-4d0f-8a20-53210f4773df}, Zigbee::ZigbeeBackendTypeDeconz, Channel: 15, ZigbeeNetwork::StateRunning)
 W | ZigbeeResource: No zigbee handler available to handle node ZigbeeNode(0xe31f, 84:2E:14:FF:FE:5B:F2:4E, _TZ3000_kdi2o9m6, TS011F, End device, RxOn:true)
 I | Zigbee: Set permit joining in network ZigbeeNetwork(00:21:2E:FF:FF:06:AA:5E, {d99f642d-1bc4-4d0f-8a20-53210f4773df}, Zigbee::ZigbeeBackendTypeDeconz, Channel: 15, ZigbeeNetwork::StateRunning) to 0 seconds "0xfffc"
 I | ZigbeeNetwork: Disable permit join on "0xfffc"
 I | Zigbee: Network permit joining changed "{d99f642d-1bc4-4d0f-8a20-53210f4773df}" false
 I | ZigbeeResource: ZigbeeNode(0xe31f, 84:2E:14:FF:FE:5B:F2:4E, _TZ3000_kdi2o9m6, TS011F, End device, RxOn:true) joined the network ZigbeeNetwork(00:21:2E:FF:FF:06:AA:5E, {d99f642d-1bc4-4d0f-8a20-53210f4773df}, Zigbee::ZigbeeBackendTypeDeconz, Channel: 15, ZigbeeNetwork::StateRunning)
 W | ZigbeeResource: No zigbee handler available to handle node ZigbeeNode(0xe31f, 84:2E:14:FF:FE:5B:F2:4E, _TZ3000_kdi2o9m6, TS011F, End device, RxOn:true)
 I | ZigbeeNetwork: Send permit join request "0xfffc" 0 s
 I | ZigbeeResource: ZigbeeNode(0xe31f, 84:2E:14:FF:FE:5B:F2:4E, _TZ3000_kdi2o9m6, TS011F, End device, RxOn:true) joined the network ZigbeeNetwork(00:21:2E:FF:FF:06:AA:5E, {d99f642d-1bc4-4d0f-8a20-53210f4773df}, Zigbee::ZigbeeBackendTypeDeconz, Channel: 15, ZigbeeNetwork::StateRunning)
 W | ZigbeeResource: No zigbee handler available to handle node ZigbeeNode(0xe31f, 84:2E:14:FF:FE:5B:F2:4E, _TZ3000_kdi2o9m6, TS011F, End device, RxOn:true)
 I | ZigbeeNetwork: Received unhandled broadcast ZDO indication APSDE-DATA.indication(Group address:"0xfffc", Destination EP:"0x01", Source EP:"0x00", Source NWK address:"0x0000", Zigbee::ZigbeeProfileDevice, ZigbeeDeviceProfile::MgmtPermitJoinRequest, ASDU: "0x0f 0x00 0x01", LQI: 192, RSSI: 3dBm)
 I | ZigbeeNetwork: Finish network reply ZigbeeNetworkReply(0x1a25178) ZigbeeNetworkReply::ErrorNoError
 I | ZigbeeNetwork: Network request sent successfully to device Request(ID:15, Zigbee::ZigbeeProfileDevice, ZigbeeDeviceProfile::MgmtPermitJoinRequest, Group address:"0xfffc", Destination EP:"0x00", Source EP:"0x00", Radius:10, QFlags<Zigbee::ZigbeeTxOption>(), "0x0f 0x00 0x01")
 I | ZigbeeNetwork: Permit join request finished successfully
 I | ZigbeeNetwork: Set permit join configuration request finished Deconz::StatusCodeSuccess

**Comment by mzanetti** [comment]
Comparing this log and the code for the relevant plugin, I can't see why it wouldn't work.
The one thing I find suspicious though, is that the whole log doesn't contain any entry from the "ZigbeeGeneric" category.

Can you please verify that you have indeed installed nymea-plugin-zigbee-generic?

**Comment by Ollipake** [comment]
Strange. The "ZigbeeGeneric" does not show there in the "Plugins", but from System update-> Install/remove software says  0.26.1+202101301756 would be installed. The timestamp seems a bit old, am i right? 

I removed the plugin. Then it suggests a 0.26.0+202102261026 which i installed.  Still it doesn't show in the "Plugins" list. Then i restarted the Nymea core and tadaa, it works! 

Do you still want some logs or other info about this case? Can you figure out why the Zigbee generic was older version?

**Comment by mzanetti** [comment]
Oh, are you (or were you) running experimental? There was an issue beginning of March that would bump the version number to 0.26.1 accidentally. If you updated your installation in those few hours it would not get you any other updates until the official version number would catch up. According to the version numbers you seem to have run into that issue.

**Comment by Ollipake** [comment]
I did indeed try experimental a while ago when i was testing the generic thermostats.
Great that this got sorted, thank you!
