### ISSUE TITLE
Keba: Thing class params should not contain IP address

### ISSUE THREAD

**Issue by mzanetti** [nymea/nymea-plugins#512]
The thing params for keba should *only* contain the MAC address. Each setup(), and also each new connection attempt should perform a network discovery and obtain the IP on demand. In order to speed up connection attempts, or cater for unreliable discoveries, the plugin *may* cache the last used IP address in the pluginStorage() but it should not be a param, ever.

(While at it, the discovery results should be cleaned up to not include IP or  MAC address information in the title. It's ok in the description, but not in the title as this will be used for the thing name)

**Comment by t-mon** [comment]
I vote against to just have the mac address. 
In case the discovery does nit work for whatever reason (we already saw that a few times), you should still be able to add it if you know the IP. The plugin itself searches the mac address if there is just the ip in the params and updates the mac address if possible. (There is a bug in the thing manager not storing the plugin param change request from plugin side).

As of now, we allow all possibilities and try to recognize and auto update the ip using the mac addresse. 

Using only the name without the ip is a good point. But testing in a setup with more then one you have no chance to distinguish them.

**Comment by mzanetti** [comment]
Fair enough, for the manual setup the IP param could be usuful. I still believe the discovery should work in any case. If the keba can be connected, there must be a way to also discover it (and even if it means sending a keba specific message to any of the ARP-scan results). So IMHO the manual setup should not be needed and with that also not the IP address. But ok, I guess we will keep on disagreeing on this one.

Anyhow, reading the code, setupThing() uses only the IP parameter. If there is no mac parameter it will be discovered as you said, but if there is a mac address, it still won't be used in setupThing(), ony the IP. 

AFACT searchNetworkDevices() will be called when:
* In postSetupThing() *if* there is no MAC (Not happening if there's a mac and an outdated IP in the params)
* When the KeContact emits rechableChanged (not happening because the private setReachable() doesn't emit it if reachable already was false.)
* After 5 minutes in the reconnect timer (This actually does seem to happen and should recover it, but only 5 minutes in)

So, IMO, even if the IP parameter will be kept, the setup code needs to bie fixed to always run the discovery.

That said, given I don't have a Keba I cannot verify what just said, this is only from reading the code, so I might have missed something, but it sure looks somewhat fishy to me if there's an outdated IP address in the params.

> Using only the name without the ip is a good point. But testing in a setup with more then one you have no chance to distinguish them.

You can actually rename them during the setup if you whish ;)
