### ISSUE TITLE
Possible bug in SG Ready plugin

### ISSUE THREAD

**Issue by lheiz** [nymea/nymea-plugins#596]
The SG Ready plugin is not working properly:

` W | ThingManager: Thing "SG Ready interface" ( "{8b975992-39a7-4698-89f0-4202699c2cfd}" ) does not have a setting with id QUuid("{d2c83778-693f-4146-a656-a8ed901c1a7f}")`

https://github.com/nymea/nymea-plugins/blob/860fbac0e83251c08bdb3d089c425c43af02b931/sgready/integrationpluginsgready.cpp#L94

I think this should be `setStateValue` instead of `setSettingValue`.

**Comment by t-mon** [comment]
Thanks, you are right, definitely a typo! #597
