### ISSUE TITLE
[request, shelly plug] add tap to switch between current and total power

### ISSUE THREAD

**Issue by Danfro** [nymea/nymea-plugins#628]
Currently in the meter section, the shelly plug does display the current power consumption. There is no other interactivity except of the menu. If the user wants to see the total consumption, one needs to open the menu and the details page or go back to the main page.

It might be nice to have an option to simply tap the button icon/circle and swap between current power and total power being displayed?

![grafik](https://user-images.githubusercontent.com/37637312/202300348-796a7d9f-ecce-487d-9570-dfb5e5a7d33e.png)

**Comment by mzanetti** [comment]
again, nothing to do with the shelly plugin. Also note, that the absolute number of total energy consumed is not really informative. Instead, you'd better enable the nymea energy view which will represent total values for days, weeks, months etc. That one also deals properly with the fact that the shelly plug will reset its counter to 0 on every power loss.

That said, we could probably still add the total value in this view in the app...

**Comment by mzanetti** [comment]
Yes, that'd be great if you could report this for the app.

As for the hint. The idea is to eventually have some sort of a welcome wizard which would ask the user for the "use cases" that should be enabled. This one would then offer the energy view. However, in order for that to be actually useful, we'll need some more use cases :D 

So yes, for now, I guess adding the raw total counter as coming from the device in this view makes sense.

**Comment by Danfro** [comment]
Ok, moved to [nymea app no.912](https://github.com/nymea/nymea-app/issues/912)
