### ISSUE TITLE
[shelly plug plugin] the current power consumption is displayed with different decimals in different pages

### ISSUE THREAD

**Issue by Danfro** [nymea/nymea-plugins#629]
In two places (plugs page,meter overview, first two screenshots), the meter displays the current power consumption with one decimal. The plugs details page and the overview display two digitals. 

In all places the same number of digitals should be displayed..

![grafik](https://user-images.githubusercontent.com/37637312/202299352-b53355ea-1d8c-4601-8aa9-22cd0ec5c4d0.png)

![grafik](https://user-images.githubusercontent.com/37637312/202299900-f4b51365-89d4-4779-80d2-b06e579ac0bf.png)

![grafik](https://user-images.githubusercontent.com/37637312/202299586-265f1c08-c9d8-4b21-9e7e-d01ab043d21b.png)

![grafik](https://user-images.githubusercontent.com/37637312/202299720-d2a6a904-d7a6-4660-b9c6-184d904e1115.png)

**Comment by mzanetti** [comment]
fwiw, this has nothing to do with the shelly plugin, but is done by the app.

**Comment by Danfro** [comment]
Moved to [nymea app no. 913](https://github.com/nymea/nymea-app/issues/913)
