### ISSUE TITLE
error created by networkdevicediscovery due to VPN in FritzBox

### ISSUE THREAD

**Issue by Danfro** [nymea/nymea-plugins#716]
My nymea log brings the following entry:

```
W | NetworkDeviceDiscovery: Already complete network device info changed during discovery process! Please report a bug if you see this message containing following 2 lines:
 W | NetworkDeviceDiscovery: NetworkDeviceInfo("someIP.1", "identical_Mac" ("AVM Audiovisuelles Marketing und Computersysteme GmbH") , hostname: "fritz.box", "eth0")
 W | NetworkDeviceDiscovery: NetworkDeviceInfo("someIP.201", "identical_Mac" ("AVM Audiovisuelles Marketing und Computersysteme GmbH") , hostname: "fritz.box", "eth0")
```

As instructed there ;-) I report a bug here.

The first device (IP ending with .1) is my router (AVM FritzBox). The second device ((IP ending with .201) is the one of the wireguard interface set in the settings of the router.

**Comment by t-mon** [comment]
Thanks for reporting it!

If both NetworkDeviceInfo  refer to one device (MAC) which has 2 network interfaces and therefore IPs to the same network this seems not to be a bug (any more). I think it is save to remove this warning in the next release. 

But it is/was very confusing when I discovered this. The reason for this log message is actually a feature of linux kernel which tells nymea we can reach the mac address using both IP addresses, very strange, 2 IPs for one MAC address, but it looks like this is possible and the network device itself takes care of delivering network packets to the right destination. So far, all situation where this log appeared where situations as described.

**Comment by t-mon** [comment]
Updated in https://github.com/nymea/nymea/pull/655
